services:
  redis-node-0:
    user: root
    container_name: redis-node-0
    image: bitnami/redis-cluster:latest
    ports:
      - 6379:6379
      - 16379:16379
    volumes:
      - ./redis_data-0:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6379'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16379'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.2

  redis-node-1:
    user: root
    container_name: redis-node-1
    image: bitnami/redis-cluster:latest
    ports:
      - 6380:6379
      - 16380:16379
    volumes:
      - ./redis_data-1:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6380'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16380'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.3

  redis-node-2:
    user: root
    container_name: redis-node-2
    image: bitnami/redis-cluster:latest
    ports:
      - 6381:6379
      - 16381:16379
    volumes:
      - ./redis_data-2:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6381'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16381'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.4

  redis-node-3:
    user: root
    container_name: redis-node-3
    image: bitnami/redis-cluster:latest
    ports:
      - 6382:6379
      - 16382:16379
    volumes:
      - ./redis_data-3:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6382'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16382'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.5

  redis-node-4:
    user: root
    container_name: redis-node-4
    image: bitnami/redis-cluster:latest
    ports:
      - 6383:6379
      - 16383:16379
    volumes:
      - ./redis_data-4:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6383'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16383'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.6
      
  redis-node-5:
    user: root
    container_name: redis-node-5
    image: bitnami/redis-cluster:latest
    ports:
      - 6384:6379
      - 16384:16379
    volumes:
      - ./redis_data-5:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6384'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16384'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.7

  redis-node-6:
    user: root
    container_name: redis-node-6
    image: bitnami/redis-cluster:latest
    ports:
      - 6385:6379
      - 16385:16379
    volumes:
      - ./redis_data-6:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6385'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16385'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.8

  redis-node-7:
    user: root
    container_name: redis-node-7
    image: bitnami/redis-cluster:latest
    ports:
      - 6386:6379
      - 16386:16379
    volumes:
      - ./redis_data-7:/bitnami/redis/data
    depends_on:
      - redis-node-0
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_REPLICAS=1'
      - 'REDIS_NODES=redis-node-0 redis-node-1 redis-node-2 redis-node-3 redis-node-4 redis-node-5 redis-node-6 redis-node-7'
      - 'REDIS_CLUSTER_CREATOR=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6386'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16386'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.9

  redis-0:
    user: root
    container_name: redis-0
    image: bitnami/redis:latest
    ports:
      - 6390:6379
      - 16390:16379
    volumes:
      - ./redis-0:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6390'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16390'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.10

  redis-1:
    user: root
    container_name: redis-1
    image: bitnami/redis:latest
    ports:
      - 6391:6379
      - 16391:16379
    volumes:
      - ./redis-1:/bitnami/redis/data
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'
      - 'REDIS_CLUSTER_DYNAMIC_IPS=no'
      - 'REDIS_CLUSTER_ANNOUNCE_IP=192.168.0.47'
      - 'REDIS_CLUSTER_ANNOUNCE_PORT=6391'
      - 'REDIS_CLUSTER_ANNOUNCE_BUS_PORT=16391'
    networks:
      redis-cluster-network:
        ipv4_address: 172.20.0.11

networks:
  redis-cluster-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16